# Site settings
title: Css animations and Scss mixins
email: 'info@danielebertella.com'
description: "Bunch of useful css animations and scss mixins that I find myself using in almost every project"
baseurl: ""
url: "http://danielebert.github.io/css-animations/"
twitter_username: '@_denb'
github_username:  'danielebert'

# Build settings
markdown: kramdown
permalink: pretty
